name: Go

on:
  push:
    tags:
    - '*'
    # branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest # [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check
      run: go vet -v ./...

    - name: Test
      run: go test ./cmd/... ./internal/...

    - name: Build
      run: go build -v ./...

