# The name of your workflow. GitHub displays the names of your workflows on your repository's actions page. 
name: trice # If you omit name, GitHub sets it to the workflow file path relative to the root of the repository.

on: # Required. The name of the GitHub event that triggers the workflow. 
  pull_request:
  push: # Triggered when code is pushed to any branch in a repository

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          # Unexpected input(s) 'key', valid inputs are ['version', 'args', 'workdir', 'install-only']
          # key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
